name: Scrap Steam Titles

on:
  workflow_dispatch:

jobs:
  scrap-steam-titles:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS: true
    steps:
      - uses: actions/checkout@v4
      - name: Scrap Steam Titles
        run: scrap-steam-titles.sh
